# Generated by Django 3.1.7 on 2021-03-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210329_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pub_date',
            new_name='registration_date',
        ),
    ]
